#!/bin/sh

# board defaults, do not change in running system. Change /env/config
# instead

global vmx
global vmx.model
global vmx.kernelno
global vmx.kernel
global vmx.dtb

global.vmx.model=254
global.vmx.kernelno=4.14
global.vmx.dtb=imx25-voipac-vmx25-${global.vmx.model}-${global.vmx.kernelno}.dtb

global.hostname=vmx25
global.linux.bootargs.base="console=ttymxc0,115200"
global.boot.default=nand-ubi
